### PR TITLE
Support msys2 bash on Windows

### PR DESCRIPTION
**Pull request by mattn**
image

image

### CODE REVIEW

**Comment by mattn** [comment]
FYI, On msys2, it is possible to convert msys2/cygwin paths into Windows native paths with using cygpath.exe. Which do you prefer?

**Comment by talal** [comment]
Thank you for taking the time to add msys2 support :)

Code-wise, your contributions look good to me. Approach-wise, I can't make a comment since I'm not familiar with msys2/cygwin.

Kindly update the [CHANGELOG.md](https://github.com/talal/mimir/blob/master/CHANGELOG.md) accordingly under `v2.1.0` heading.

Once that is done, I'll merge this PR.

**Review by talal — APPROVED** [review]

**Comment by mattn** [comment]
please point me if need to add more description in CHANGELOG.md .

**Comment by talal** [comment]
The comment you added is perfect. Thanks!

PR is merged :)

**Pull request merged**
